const users = [
    {
      firstName: 'John',
      lastName: 'Doe',
      email: 'john@example.com',
      password: 'password123',
      userName: 'john_doe',
      role: 'student',
    },
    {
      firstName: 'Jane',
      lastName: 'Smith',
      email: 'jane@example.com',
      password: 'securepass456',
      userName: 'jane_smith',
      role: 'teacher',
    },
    {
      firstName: 'Admin',
      lastName: 'User',
      email: 'admin@example.com',
      password: 'adminpass789',
      userName: 'admin_user',
      role: 'admin',
    },{
        firstName: 'Aarav',
        lastName: 'Gupta',
        email: 'aarav@example.com',
        password: 'password123',
        userName: 'aarav_gupta',
        role: 'student',
      },
      {
        firstName: 'Aditi',
        lastName: 'Sharma',
        email: 'aditi@example.com',
        password: 'securepass456',
        userName: 'aditi_sharma',
        role: 'teacher',
      },
      {
        firstName: 'Amit',
        lastName: 'Patel',
        email: 'amit@example.com',
        password: 'adminpass789',
        userName: 'amit_patel',
        role: 'admin',
      },
      {
        firstName: 'Kavya',
        lastName: 'Singh',
        email: 'kavya@example.com',
        password: 'password123',
        userName: 'kavya_singh',
        role: 'student',
      },
      {
        firstName: 'Rahul',
        lastName: 'Verma',
        email: 'rahul@example.com',
        password: 'securepass456',
        userName: 'rahul_verma',
        role: 'teacher',
      },
      {
        firstName: 'Neha',
        lastName: 'Choudhury',
        email: 'neha@example.com',
        password: 'adminpass789',
        userName: 'neha_choudhury',
        role: 'student',
      },
      {
        firstName: 'Sanjay',
        lastName: 'Mishra',
        email: 'sanjay@example.com',
        password: 'password123',
        userName: 'sanjay_mishra',
        role: 'teacher',
      },
      {
        firstName: 'Ananya',
        lastName: 'Thakur',
        email: 'ananya@example.com',
        password: 'securepass456',
        userName: 'ananya_thakur',
        role: 'student',
      },
      {
        firstName: 'Rajesh',
        lastName: 'Kumar',
        email: 'rajesh@example.com',
        password: 'adminpass789',
        userName: 'rajesh_kumar',
        role: 'teacher',
      },
      {
        firstName: 'Divya',
        lastName: 'Agarwal',
        email: 'divya@example.com',
        password: 'password123',
        userName: 'divya_agarwal',
        role: 'student',
      },
  ];

  module.exports = users